title: Kristin Sellers 
email: kristinmsellers@gmail.com
url: https://github.com/kristinsellers/freelancer-theme
description: I'm a portland-based cartographer that specializes in mapping for publication. 
keywords: cartography, data analytics, mapping, design
skills: "Cartographer - Data Analyst - Designer"

