title: Kristin Sellers 
email: kristinmsellers@gmail.com
url: https://github.com/kristinsellers/freelancer-theme
description: I'm a portland-based cartographer that specializes in mapping for publication. 
keywords: cartography, data analytics, mapping, design
skills: "Cartographer - Data Analyst - Designer"

---
layout: default
modal-id: 1
date: 2020-01-18
img: cabin.png
alt: image-alt
project-date: 2024
client: Fullerton College Geography Department
category: Cartography
description: Created nine maps for an open source environmental justice atlas. 

---
